### ISSUE TITLE
Add Message Result

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.MicrosoftTeams#2]
The Slack and Gitter Addins have the concept of a Message Result, which indicates whether the message was delivered successfully or not.  Are you planning on adding something similar for Microsoft Teams also?

**Comment by devlead** [comment]
@gep13 actually already added that to 0.2.0, the aliases now return a `HttpStatusCode` from the aliases.

These are the known values from the API (also documented in the xmldoc)
![image](https://cloud.githubusercontent.com/assets/1647294/19967424/6c7150a4-a1d0-11e6-966f-5675e7ae6a49.png)

**Comment by gep13** [comment]
Ah, cool.  I was going by the example on the readme 😄
