### ISSUE TITLE
MessageCard is missing potentialAction Array

### ISSUE THREAD

**Issue by frozenskys** [cake-contrib/Cake.MicrosoftTeams#3]
The [Office 365 Connectors API Reference](https://dev.outlook.com/Connectors/Reference) states

`potentialAction Schema.org/ViewAction[]` This array of Schema.org/ViewAction objects will power the action links found at the bottom of the card. 

Which would be useful for giving links directly to the CI artifacts, test results, etc.

**Comment by devlead** [comment]
Fixed by #5
