### ISSUE TITLE
MessageCard is Missing themeColor property

### ISSUE THREAD

**Issue by frozenskys** [cake-contrib/Cake.MicrosoftTeams#4]
The [Office 365 Connectors API Reference](https://dev.outlook.com/Connectors/Reference) states that a ConnectorCard can have an optional themeColor property

`themeColor` Color Hex Value ex: #737373 Accent color used for branding or indicating status in the card. 

Which could be used for build status etc.

**Comment by devlead** [comment]
Have you gotten that to work though? I had mixed results with its actual effect on how messages are displayed in Teams.

**Comment by frozenskys** [comment]
Didn't work with teams desktop app - but as the teams functionality is based on groups you can use the same code with a different endpoint to add cards to an Office365 group - so I assume it will come to Teams.
![screenshot_1](https://cloud.githubusercontent.com/assets/28024/20143908/c43ee01e-a692-11e6-8a10-210d7f23fd33.png)

**Comment by devlead** [comment]
Cool 👍

**Comment by devlead** [comment]
Added by #8
