### ISSUE TITLE
Upgrade to VS2017 and add .NET Core target

### ISSUE THREAD

**Issue by RLittlesII** [cake-contrib/Cake.MicrosoftTeams#9]
So addin can be loaded from Cake CoreCLR runner

**Comment by devlead** [comment]
It's already 2017 & multi targeting, lacks build script though ;)

**Comment by RLittlesII** [comment]
Sorry for that.  I was taking a quick pass through the list.  I see that now.  Maybe we can satisfy this by handling #6 ?

**Comment by devlead** [comment]
Yip👍

**Comment by RLittlesII** [comment]
@devlead I am closing this issue.  Cake.Recipe seems to be setup, and I have multi target libraries.
